# Generated by Django 5.2 on 2026-06-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='document_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
    ]
