# Generated by Django 5.2 on 2026-06-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_kyc_document_back_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_selfies/'),
        ),
    ]
