# Generated by Django 5.2 on 2026-06-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_kyc_selfie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='document_back_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='kyc_documents/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='document_image',
            field=models.ImageField(max_length=255, upload_to='kyc_documents/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='selfie_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='kyc_selfies/'),
        ),
    ]
