# Generated by Django 5.2 on 2026-06-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_kyc_document_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('completed', 'Completed'), ('failed', 'Failed')], default='unpaid', max_length=20),
        ),
    ]
